services:
  - type: web
    name: resume-screening-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python create_superuser.py
    startCommand: gunicorn resume_screening_application.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: resume_screening_application.settings
      - key: PYTHON_VERSION
        value: 3.10
